Add Swerve API documentation
CrossTheRoadElec/PhoenixPro-Documentation pull request #93
Opened 2023-09-13 22:51 UTC by daltzctr

Limited to the API for now. Tuner functionality will be in a separate PR.

2023-09-14 00:26 UTC, daltzctr commented
I probably missed a couple of bits, but the basics are done. Note that it's missing a lot of API doc links

2023-09-15 21:56 UTC, CoryNessCTR requested changes

2023-09-15 21:56 UTC, CoryNessCTR commented on source/docs/api-reference/api-usage/swerve/swerve-overview.rst
> +  * Integrates cleanly into WPILib `commandbased <https://docs.wpilib.org/en/stable/docs/software/commandbased/index.html>`__ framework via ``CommandSwerveDrivetrain`` (Java).
Note that `CommandSwerveDrivetrain` only exists in the example project, it's not part of the native API. We can't depend on the NewCommands vendordep in our API.

2023-09-15 21:56 UTC, CoryNessCTR commented on source/docs/api-reference/api-usage/swerve/swerve-overview.rst
> +    * Supports common scenarios such as X module (point all modules toward the center of the robot).
```suggestion
    * Supports common scenarios such as X mode (point all modules toward the center of the robot).
```

2023-09-15 21:56 UTC, CoryNessCTR commented on source/docs/api-reference/api-usage/swerve/swerve-overview.rst
> +  * Simply call ``updateSimState`` (Java) in ``simulationPeriodic()`` (`Java <https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/IterativeRobotBase.html#simulationPeriodic()>
Maybe make a note that this is done already if you're using the example `CommandSwerveDrivetrain` class

2023-09-15 21:56 UTC, CoryNessCTR commented on source/docs/api-reference/api-usage/swerve/swerve-overview.rst
> +  * Combine with `PRO <https://store.ctr-electronics.com/phoenix-pro/>`__ (optional) and `CANFD <https://store.ctr-electronics.com/canivore/>`__ to utilize :ref:`timesync <docs/api-reference/api-usag
```suggestion
  * Combine with `Phoenix Pro <https://store.ctr-electronics.com/phoenix-pro/>`__ (optional) and a `CANivore<https://store.ctr-electronics.com/canivore/>`__ (optional) with :ref:`timesync <docs/api-reference/api-usage/status-signals:canivore timesync>` for even more performance.
```
Both are optional, both give fairly significant improvements.

2023-09-15 21:56 UTC, CoryNessCTR commented on source/docs/api-reference/api-usage/swerve/swerve-requests.rst
> +
We can mention how it's possible to make your own SwerveRequests as well

2023-09-15 21:56 UTC, CoryNessCTR commented on source/docs/api-reference/api-usage/swerve/swerve-simulation.rst
> +            updateSimState(0.02, 12);
This isn't necessary with the `CommandSwerveDrivetrain` because it occurs in the subsystem's `simulationPeriodic` instead.

2023-09-18 19:48 UTC, CoryNessCTR approved these changes

2023-09-18 19:51 UTC, merged